### ISSUE TITLE
FIX: Formatting of documentation websites

### ISSUE THREAD

**Issue by ninamiolane** [pyt-team/pyt-team.github.io#15]
# What?

The formatting of the doc websites has been broken, now it looks like the screenshot below. We should fix it.

# How?

The break could come from a recent attempt of creating one single entry-point website, see: issue:
 https://github.com/orgs/pyt-team/projects/2/views/1?pane=issue&itemId=39049106

The break could also come from the sphinx version, which could have been updated and become incompatible with other formatting packages.

![Image](https://user-images.githubusercontent.com/8267869/269313350-cf253e42-71bf-46ec-99ae-0932a519ea3e.png)

**Comment by devendragovil** [comment]
@ninamiolane  I am not able to reproduce the issue locally as of now. I am thinking it might be an issue with the way Github Pages was setup. Is it possible to grant me higher privileges to be able to see that. I would also like to create and experiment with a new repo (for Github Pages) to see if I can make it work and reproduce the issues.

**Comment by ninamiolane** [comment]
@devendragovil Thank you so much for looking into this. I am also confused why this happened. I have granted you admin access to this repository. Feel free to try everything you can think of!

**Comment by devendragovil** [comment]
@ninamiolane 

Eureka!!! And I am frankly laughing at the thing that fixed it! 

It was about adding an empty file in the root of the repository. Can you believe that! It was such an excruciatingly slow process to discover this one!
